var laptops = [
  {
    key: "B01LT692RK",
    category: "laptop",
    name: "ASUS E200HA",
    seller: "Asus",
    wholePrice: "199",
    priceFraction: "00",
    stock: 41,
    star: 3,
    starCount: 4074,
    img: "https://images-na.ssl-images-amazon.com/images/I/51zIMkOI70L._AC_US218_.jpg",
    url: "https://www.amazon.com/Lightweight-11-6-inch-Quad-Core-Microsoft-Subscription/dp/B01LT692RK/ref=sr_1_19?s=electronics&ie=UTF8&qid=1499124890&sr=1-19&keywords=laptop",
    features: [
      { description: "Display Size", value: "11.6 inches" },
      { description: "Computer Memory Size", value: "4 GB" },
      { description: "Operating System", value: "Windows 10" },
      { description: "Hard Disk Size", value: "32 GB" },
      { description: "Cpu Model Family", value: "intel atom" },
    ],
    price: 199,
    shipping: 3.99,
  },
  {
    key: "B071LB1GG4",
    category: "laptop",
    name: "Samsung XE510C24-K01US Chromebook Pro",
    seller: "Samsung",
    wholePrice: "549",
    priceFraction: "99",
    stock: 91,
    star: 4,
    starCount: 1157,
    img: "https://images-na.ssl-images-amazon.com/images/I/41QCsi3gCrL._AC_US218_.jpg",
    url: "https://www.amazon.com/Samsung-XE510C24-K01US-Chromebook-Pro/dp/B071LB1GG4/ref=sr_1_20?s=electronics&ie=UTF8&qid=1499124890&sr=1-20&keywords=laptop",
    features: [
      { description: "Display Size", value: "12.3 inches" },
      { description: "Computer Memory Size", value: "4 GB" },
      { description: "Operating System", value: "Chrome" },
      { description: "Connectivity Technology", value: "wireless" },
      { description: "Hardware Platform", value: "Chrome" },
    ],
    price: 549.99,
    shipping: 0,
  },
  {
    key: "B01CVOLVPA",
    category: "laptop",
    name: "Acer Chromebook 14",
    seller: "Acer",
    wholePrice: "294",
    priceFraction: "98",
    stock: 57,
    star: 4,
    starCount: 678,
    img: "https://images-na.ssl-images-amazon.com/images/I/518PvURfFsL._AC_US218_.jpg",
    url: "https://www.amazon.com/Acer-Chromebook-Aluminum-Quad-Core-CB3-431-C5FM/dp/B01CVOLVPA/ref=sr_1_21?s=electronics&ie=UTF8&qid=1499124890&sr=1-21&keywords=laptop",
    features: [
      { description: "Display Size", value: "14 inches" },
      { description: "Computer Memory Size", value: "4 GB" },
      { description: "Operating System", value: "Chrome" },
      { description: "Hard Disk Size", value: "32 GB" },
      { description: "Cpu Model Family", value: "celeron" },
    ],
    price: 294.98,
    shipping: 7.99,
  },
  {
    key: "B01EIUOSRS",
    category: "laptop",
    name: "Apple MMGF2LL/A MacBook Air",
    seller: "Apple",
    wholePrice: "799",
    priceFraction: "99",
    stock: 51,
    star: 4,
    starCount: 3295,
    img: "https://images-na.ssl-images-amazon.com/images/I/41AerRC5u6L._AC_US218_.jpg",
    url: "https://www.amazon.com/Apple-MMGF2LL-MacBook-13-3-Inch-Laptop/dp/B01EIUOSRS/ref=sr_1_22?s=electronics&ie=UTF8&qid=1499124890&sr=1-22&keywords=laptop",
    features: [
      { description: "Display Size", value: "13.3 inches" },
      { description: "Computer Memory Size", value: "8 GB" },
      { description: "Operating System", value: "Mac OS X" },
      { description: "Hard Disk Size", value: "128 GB" },
      { description: "Cpu Model Family", value: "core i5" },
    ],
    price: 799.99,
    shipping: 7.99,
  },
  {
    key: "B01JLCKP34",
    category: "laptop",
    name: "HP Stream Laptop PC 14-ax010nr",
    seller: "HP",
    wholePrice: "219",
    priceFraction: "99",
    stock: 62,
    star: 3,
    starCount: 2286,
    img: "https://images-na.ssl-images-amazon.com/images/I/51h+5rcpStL._AC_US218_.jpg",
    url: "https://www.amazon.com/HP-Stream-14-ax010nr-Celeron-Personal/dp/B01JLCKP34/ref=sr_1_23?s=electronics&ie=UTF8&qid=1499124890&sr=1-23&keywords=laptop",
    features: [
      { description: "Display Size", value: "14 inches" },
      { description: "Computer Memory Size", value: "4 GB" },
      { description: "Operating System", value: "Windows 10" },
      { description: "Hard Disk Size", value: "32 GB" },
      { description: "Cpu Model Family", value: "celeron" },
    ],
    price: 219.99,
    shipping: 7.99,
  },
  {
    key: "B071SF41Y9",
    category: "laptop",
    name: "Microsoft Surface Pro",
    seller: "Microsoft",
    wholePrice: "1,294",
    priceFraction: "99",
    stock: 99,
    star: 3,
    starCount: 461,
    img: "https://images-na.ssl-images-amazon.com/images/I/418g6Q3eTHL._AC_US218_.jpg",
    url: "https://www.amazon.com/Microsoft-Surface-Intel-Core-256GB/dp/B071SF41Y9/ref=sr_1_25?s=electronics&ie=UTF8&qid=1499124890&sr=1-25&keywords=laptop",
    features: [
      { description: "Display Size", value: "12.3 inches" },
      { description: "Computer Memory Size", value: "8 GB" },
      { description: "Operating System", value: "Windows 10 Pro" },
      { description: "Cpu Model Family", value: "8032" },
      { description: "Display Technology", value: "LCD" },
    ],
    price: 1,
    shipping: 7.99,
  },
  {
    key: "B01N5P6TJW",
    category: "laptop",
    name: "Samsung Chromebook 3",
    seller: "Samsung",
    wholePrice: "169",
    priceFraction: "00",
    stock: 36,
    star: 3,
    starCount: 2527,
    img: "https://images-na.ssl-images-amazon.com/images/I/41XCWymAVaL._AC_US218_.jpg",
    url: "https://www.amazon.com/Samsung-Chromebook-11-6-16GB-XE500C13-K04US/dp/B01N5P6TJW/ref=sr_1_26?s=electronics&ie=UTF8&qid=1499124890&sr=1-26&keywords=laptop",
    features: [
      { description: "Display Size", value: "11.6 inches" },
      { description: "Computer Memory Size", value: "4 GB" },
      { description: "Operating System", value: "Chrome OS" },
      { description: "Hard Disk Size", value: "16 GB" },
      { description: "Cpu Model Family", value: "8032" },
    ],
    price: 169,
    shipping: 7.99,
  },
  {
    key: "B01M8J68W0",
    category: "laptop",
    name: "Kayond Bule Rose",
    seller: "kayond",
    wholePrice: "11",
    priceFraction: "99",
    stock: 86,
    star: 4,
    starCount: 2359,
    img: "https://images-na.ssl-images-amazon.com/images/I/51zDiHyaE1L._AC_US218_.jpg",
    url: "https://www.amazon.com/gp/slredirect/picassoRedirect.html/ref=pa_sp_btf_electronics_sr_pg1_1?ie=UTF8&adId=A03286941HBVHVI1MCDYH&url=https%3A%2F%2Fwww.amazon.com%2FKayond-Pattern-Canvas-12-5inch-macbook%2Fdp%2FB01M8J68W0%2Fref%3Dsr_1_27%3Fs%3Delectronics%26ie%3DUTF8%26qid%3D1499124890%26sr%3D1-27-spons%26keywords%3Dlaptop%26psc%3D1&qualifier=1499124889&id=6267744216991374&widgetName=sp_btf",
    features: [],
    price: 11.99,
    shipping: 3.99,
  },
  {
    key: "B072TY6LZL",
    category: "laptop",
    name: "Microsoft Surface ",
    seller: "Megoo",
    wholePrice: "17",
    priceFraction: "77",
    stock: 75,
    star: 0,
    starCount: 3019,
    img: "https://images-na.ssl-images-amazon.com/images/I/51YGz9inR9L._AC_US218_.jpg",
    url: "https://www.amazon.com/gp/slredirect/picassoRedirect.html/ref=pa_sp_btf_electronics_sr_pg1_2?ie=UTF8&adId=A08835611S2XQ8K5PH7WW&url=https%3A%2F%2Fwww.amazon.com%2FMicrosoft-Protector-Megoo-Tempered-Anti-scratch%2Fdp%2FB072TY6LZL%2Fref%3Dsr_1_28%3Fs%3Delectronics%26ie%3DUTF8%26qid%3D1499124890%26sr%3D1-28-spons%26keywords%3Dlaptop%26psc%3D1&qualifier=1499124889&id=6267744216991374&widgetName=sp_btf",
    features: [],
    price: 17.77,
    shipping: 3.99,
  },
];

export default laptops;
